<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\AssetType;
use App\Models\AssetCustomField;

class ITGlueAssetSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $types = [
            // 🏢 MSP & CLIENT FOUNDATION MODULES
            'MSP Information' => [
                'MSP Name' => 'text',
                'Legal Business Name' => 'text',
                'Registration Number' => 'text',
                'Tax ID / VAT' => 'text',
                'Primary Address' => 'text',
                'Country' => 'text',
                'Timezone' => 'text',
                'NOC Phone Number' => 'text',
                'Emergency Support Line' => 'text',
                'Main Email Address' => 'text',
                'Website' => 'text',
                'SLA Coverage Hours' => 'text',
                'Billing Cycle' => 'text',
                'After-Hours Rate' => 'text',
                'Banking Details' => 'text',
                'Support Portal URL' => 'text',
                'PSA Tool Used' => 'text',
                'RMM Tool Used' => 'text',
                'Documentation Platform URL' => 'text',
                'Escalation Matrix Link' => 'text',
                'Notes' => 'textarea',
            ],
            'Primary MSP Information' => [
                'Primary Account Manager' => 'text',
                'Technical Account Manager' => 'text',
                'Primary Support Email' => 'text',
                'Tier 1 Contact' => 'text',
                'Tier 2 Contact' => 'text',
                'Escalation Contact' => 'text',
                'NOC Supervisor' => 'text',
                'On-Call Rotation Link' => 'text',
                'Office Hours' => 'text',
                'Emergency Process' => 'text',
                'Internal Ticket Category Mapping' => 'text',
            ],
            'Client Support Scope' => [
                'Managed / Co-managed / Advisory' => 'text',
                'Included Services' => 'textarea',
                'Excluded Services' => 'textarea',
                'SLA Response Time' => 'text',
                'SLA Resolution Target' => 'text',
                'After Hours Coverage (Yes/No)' => 'select:Yes,No',
                'Supported Locations' => 'text',
                'Supported Devices Count' => 'number',
                'Supported Users Count' => 'number',
                'Onboarding Date' => 'date',
                'Contract End Date' => 'date',
                'Backup Responsibility' => 'text',
                'Security Monitoring Responsibility' => 'text',
                'Licensing Responsibility' => 'text',
                'Patch Management Included' => 'select:Yes,No',
                'Cloud Services Managed' => 'text',
                'Vendor Liaison Included' => 'select:Yes,No',
                'Notes' => 'textarea',
            ],

            // 🧱 INFRASTRUCTURE & ASSET MODULES
            'Core Assets' => [
                // Note: Most of these map to core columns, but defining them lets us show them in "Details" too if desired.
                // However, based on user request, they want these fields visible in spec sections.
                // We will add them as custom fields to be safe.
                'Asset Name' => 'text',
                'Asset Tag' => 'text',
                'Serial Number' => 'text',
                'Manufacturer' => 'text',
                'Model' => 'text',
                'Asset Type' => 'text',
                'Location' => 'text',
                'Warranty Expiry' => 'date',
                'Purchase Date' => 'date',
                'End of Life' => 'date',
                'Status (Active/Retired)' => 'select:Active,Retired',
                'Assigned User' => 'text',
                'IP Address' => 'text',
                'MAC Address' => 'text',
                'OS Version' => 'text',
                'Monitoring Enabled (Yes/No)' => 'select:Yes,No',
                'RMM Agent Installed (Yes/No)' => 'select:Yes,No',
                'Linked Credentials' => 'text', // Placeholder for relation
                'Linked Documents' => 'text',   // Placeholder for relation
                'Notes' => 'textarea',
            ],
            'Configurations' => [
                'Configuration Name' => 'text',
                'Type (Firewall, AD, App)' => 'text',
                'Version' => 'text',
                'Environment (Prod/Test/Dev)' => 'select:Prod,Test,Dev',
                'Export File Attached' => 'select:Yes,No',
                'Config Backup Date' => 'date',
                'Last Reviewed' => 'date',
                'Reviewed By' => 'text',
                'Risk Level' => 'text',
                'Linked Asset' => 'text',
                'Change History' => 'textarea',
            ],
            // 'Contacts', 'Documents', 'Locations', 'Passwords' are core tables, 
            // but we add Asset Types for them just in case they want flexible custom fields on top.
            // Skipping to avoid confusion with core features unless explicitly requested as *Assets*.
            // User listed them as modules. The Controller handles them. 
            // We only seed "Asset Types" for things that go into the `assets` table.
            
            // ☁️ APPS & SERVICES
            'Active Directory' => [
                'Domain Name' => 'text',
                'Forest Level' => 'text',
                'Domain Level' => 'text',
                'FSMO Role Owners' => 'text',
                'Global Catalog Servers' => 'text',
                'DC List' => 'textarea',
                'Azure AD Sync Enabled' => 'select:Yes,No',
                'Time Source' => 'text',
                'SYSVOL Health' => 'text',
                'AD Sites' => 'text',
                'Password Policy' => 'text',
                'Backup Enabled' => 'select:Yes,No',
                'Notes' => 'textarea',
            ],
            'Applications' => [
                'App Name' => 'text',
                'Version' => 'text',
                'Vendor' => 'text',
                'Hosting Type (OnPrem/Cloud)' => 'select:OnPrem,Cloud',
                'Server Hosted On' => 'text',
                'URL' => 'text',
                'License Count' => 'number',
                'License Expiry' => 'date',
                'Support Contact' => 'text',
                'Criticality Level' => 'text',
                'Backup Method' => 'text',
                'DR Plan' => 'textarea',
                'Notes' => 'textarea',
            ],
            'Backup' => [
                'Backup Solution' => 'text',
                'Backup Type' => 'text',
                'Backup Frequency' => 'text',
                'Retention Policy' => 'text',
                'Immutable Storage' => 'select:Yes,No',
                'Last Successful Backup' => 'date',
                'Last Restore Test' => 'date',
                'Offsite Location' => 'text',
                'Encryption Enabled' => 'select:Yes,No',
                'Alerting Enabled' => 'select:Yes,No',
                'Notes' => 'textarea',
            ],
            'Email' => [
                'Platform (365 / GSuite / Exchange)' => 'text',
                'Tenant ID' => 'text',
                'MX Records' => 'textarea',
                'SPF Config' => 'text',
                'DKIM Enabled' => 'select:Yes,No',
                'DMARC Policy' => 'text',
                'Admin Accounts' => 'textarea',
                'Mailbox Count' => 'number',
                'Backup Solution' => 'text',
                'Security Policies' => 'textarea',
                'Notes' => 'textarea',
            ],
            'Internet / WAN' => [
                'ISP Name' => 'text',
                'Circuit ID' => 'text',
                'Static IP' => 'text',
                'Gateway' => 'text',
                'Subnet' => 'text',
                'Bandwidth' => 'text',
                'SLA' => 'text',
                'Failover Config' => 'text',
                'Router Model' => 'text',
                'Support Contact' => 'text',
                'Notes' => 'textarea',
            ],
            'LAN' => [
                'Subnet' => 'text',
                'VLAN List' => 'textarea',
                'DHCP Server' => 'text',
                'DNS Server' => 'text',
                'Gateway' => 'text',
                'Core Switch' => 'text',
                'IP Scheme' => 'text',
                'ACL Summary' => 'textarea',
                'Notes' => 'textarea',
            ],
            'Licensing' => [
                'Product' => 'text',
                'Vendor' => 'text',
                'License Key (Encrypted)' => 'text',
                'Number of Seats' => 'number',
                'Expiry Date' => 'date',
                'Auto Renew' => 'select:Yes,No',
                'Assigned Users' => 'textarea',
                'Notes' => 'textarea',
            ],
            'Mobile Devices' => [
                'Device Type' => 'text',
                'Model' => 'text',
                'IMEI' => 'text',
                'Assigned User' => 'text',
                'MDM Enrolled' => 'select:Yes,No',
                'OS Version' => 'text',
                'SIM Provider' => 'text',
                'Status' => 'text',
                'Notes' => 'textarea',
            ],
            'Managed Printers' => [
                'Model' => 'text',
                'IP Address' => 'text',
                'Location' => 'text',
                'Serial' => 'text',
                'Toner Type' => 'text',
                'Lease Expiry' => 'date',
                'Monitoring Enabled' => 'select:Yes,No',
                'Vendor Contact' => 'text',
                'Notes' => 'textarea',
            ],
            'Vendor Management' => [
                'Vendor Name' => 'text',
                'Vendor Type' => 'text',
                'Account Number' => 'text',
                'Support Number' => 'text',
                'SLA' => 'text',
                'Escalation Contact' => 'text',
                'Contract Expiry' => 'date',
                'Notes' => 'textarea',
            ],
            'Shared Drives' => [
                'Drive Name' => 'text',
                'Server' => 'text',
                'Path' => 'text',
                'Access Group' => 'text',
                'Owner' => 'text',
                'Backup Status' => 'text',
                'Data Sensitivity' => 'text',
                'Notes' => 'textarea',
            ],
            // 🌍 DOMAIN & SSL TRACKING
            'Domains' => [
                'Domain Name' => 'text',
                'Registrar' => 'text',
                'Expiry Date' => 'date',
                'Auto Renew' => 'select:Yes,No',
                'Name Servers' => 'text',
                'DNS Hosted At' => 'text',
                'WHOIS Privacy' => 'select:Yes,No',
                'Linked Email Tenant' => 'text',
                'Notes' => 'textarea',
            ],
            'SSL Tracker' => [
                'Domain' => 'text',
                'Issuer' => 'text',
                'Expiry Date' => 'date',
                'Auto Renewal' => 'select:Yes,No',
                'Installed On' => 'text',
                'Certificate Type' => 'text',
                'Last Validation' => 'date',
                'Notes' => 'textarea',
            ],
            // 👤 USER & GROUP CONFIGURATION
            'Users' => [
                'Full Name' => 'text',
                'Username' => 'text',
                'Email' => 'text',
                'Department' => 'text',
                'Role' => 'text',
                'Office Location' => 'text',
                'MFA Status' => 'text',
                'License Assigned' => 'text',
                'Manager' => 'text',
                'Privileged Account (Yes/No)' => 'select:Yes,No',
                'Last Logon' => 'date',
                'Status' => 'text',
            ],
            'Groups' => [
                'Group Name' => 'text',
                'Type (Security/Distribution)' => 'text',
                'Members' => 'textarea',
                'Scope' => 'text',
                'Permissions' => 'textarea',
                'Owner' => 'text',
            ],
            // 🌐 NETWORKING
            'Router' => [
                'Model' => 'text',
                'WAN IP' => 'text',
                'Firmware Version' => 'text',
                'Serial' => 'text',
                'Admin Access Method' => 'text',
                'Backup Config Stored' => 'select:Yes,No',
                'VPN Enabled' => 'select:Yes,No',
                'Uptime' => 'text',
                'Notes' => 'textarea',
            ],
            'Wireless' => [
                'Controller Model' => 'text',
                'SSIDs' => 'textarea',
                'Security Type' => 'text',
                'Captive Portal' => 'select:Yes,No',
                'VLAN Mapping' => 'text',
                'Notes' => 'textarea',
            ],
            'Network Switch' => [
                'Model' => 'text',
                'Serial' => 'text',
                'Firmware' => 'text',
                'Ports Count' => 'number',
                'VLANs' => 'text',
                'PoE Enabled' => 'select:Yes,No',
                'Stacking Config' => 'text',
                'Notes' => 'textarea',
            ],
            'SAN Storage' => [
                'Vendor' => 'text',
                'Model' => 'text',
                'RAID Level' => 'text',
                'Capacity' => 'text',
                'Used Space' => 'text',
                'Connected Hosts' => 'text',
                'Firmware' => 'text',
                'Backup Status' => 'text',
            ],
            'VPN' => [
                'VPN Type' => 'text',
                'Authentication Method' => 'text',
                'MFA Enabled' => 'select:Yes,No',
                'User Count' => 'number',
                'Linked Firewall' => 'text',
                'Notes' => 'textarea',
            ],
            // 🖥️ SERVERS
            'Servers - Windows' => [
                'Server Name' => 'text',
                'Role (DC/File/App)' => 'text',
                'OS Version' => 'text',
                'Build Number' => 'text',
                'IP Address' => 'text',
                'CPU' => 'text',
                'RAM' => 'text',
                'Disk Layout' => 'text',
                'Antivirus' => 'text',
                'Backup Enabled' => 'select:Yes,No',
                'Last Patch Date' => 'date',
            ],
            'Servers - ESXi' => [
                'ESXi Version' => 'text',
                'Hostname' => 'text',
                'vCenter' => 'text',
                'CPU' => 'text',
                'RAM' => 'text',
                'Datastores' => 'text',
                'Connected VMs' => 'textarea',
                'NIC Teaming' => 'text',
                'Notes' => 'textarea',
            ],
            'Server - Physical' => [ // User wrote "Server - Physical"
                'Rack Location' => 'text',
                'BIOS Version' => 'text',
                'RAID Config' => 'text',
                'iDRAC/iLO IP' => 'text',
                'Power Supply Redundancy' => 'select:Yes,No',
            ],
            'NAS Storage' => [
                'Model' => 'text',
                'RAID' => 'text',
                'Capacity' => 'text',
                'Backup Config' => 'text',
                'Network Bonding' => 'text',
            ],
            // 📝 ONBOARDING MODULES
            'MSP Onboarding Form' => [
                'Client Name' => 'text',
                'Primary Contact' => 'text',
                'Current IT Provider' => 'text',
                'Network Diagram Provided' => 'select:Yes,No',
                'Admin Access Provided' => 'select:Yes,No',
                'Backup Details' => 'textarea',
                'Firewall Access' => 'textarea',
                'Cloud Tenant Access' => 'textarea',
                'Licensing Overview' => 'textarea',
                'RMM Installed' => 'select:Yes,No',
                'Password Dump Completed' => 'select:Yes,No',
            ],
            'SD Onboarding' => [
                'Ticketing Workflow' => 'textarea',
                'Escalation Rules' => 'textarea',
                'User Onboarding Process' => 'textarea',
                'User Offboarding Process' => 'textarea',
                'Access Matrix' => 'textarea',
                'Critical Vendors' => 'textarea',
            ],
        ];

        foreach ($types as $typeName => $fields) {
            $type = AssetType::firstOrCreate(['name' => $typeName]);

            foreach ($fields as $fieldName => $fieldType) {
                // We use firstOrCreate but if the field type is different we might want to update it.
                // For simplicity in this demo, firstOrCreate is fine.
                AssetCustomField::firstOrCreate([
                    'asset_type_id' => $type->id,
                    'name' => $fieldName,
                ], [
                    'field_type' => $fieldType
                ]);
            }
        }
    }
}
